# NOTE: setup_db.py is the authoritative source of question classifications.
# This file is a snapshot used at classification time; if you regenerate
# setup_db from this file, double-check against setup_db.py first.
QUESTIONS_2025 = """\
_ensure(Question, {'question_id': '2025Paper1Q1'}, marks=4, question_id='2025Paper1Q1', question_number='1', video='', paper='2025 Paper 1', topics='binomial_theorem', subtopics='binomial_expansion')
_ensure(Question, {'question_id': '2025Paper1Q2'}, marks=3, question_id='2025Paper1Q2', question_number='2', video='', paper='2025 Paper 1', topics='differentiation', subtopics='quotient_rule')
_ensure(Question, {'question_id': '2025Paper1Q3'}, marks=2, question_id='2025Paper1Q3', question_number='3', video='', paper='2025 Paper 1', topics='complex_numbers', subtopics='basic_operations')
_ensure(Question, {'question_id': '2025Paper1Q4'}, marks=6, question_id='2025Paper1Q4', question_number='4', video='', paper='2025 Paper 1', topics='matrices', subtopics='matrix_algebra_identities,determinant')
_ensure(Question, {'question_id': '2025Paper1Q5'}, marks=2, question_id='2025Paper1Q5', question_number='5', video='', paper='2025 Paper 1', topics='integration', subtopics='standard_integrals')
_ensure(Question, {'question_id': '2025Paper1Q6'}, marks=4, question_id='2025Paper1Q6', question_number='6', video='', paper='2025 Paper 1', topics='functions_graphs,partial_fractions', subtopics='asymptotes,improper_rational_fraction')
_ensure(Question, {'question_id': '2025Paper1Q7'}, marks=5, question_id='2025Paper1Q7', question_number='7', video='', paper='2025 Paper 1', topics='differential_equations', subtopics='first_order_variables_separable')
_ensure(Question, {'question_id': '2025Paper1Q8a'}, marks=4, question_id='2025Paper1Q8a', question_number='8a', video='', paper='2025 Paper 1', topics='systems_of_equations', subtopics='gaussian_elimination')
_ensure(Question, {'question_id': '2025Paper1Q8b'}, marks=3, question_id='2025Paper1Q8b', question_number='8b', video='', paper='2025 Paper 1', topics='vectors', subtopics='3d_lines,3d_planes')
_ensure(Question, {'question_id': '2025Paper1Q8c'}, marks=2, question_id='2025Paper1Q8c', question_number='8c', video='', paper='2025 Paper 1', topics='vectors', subtopics='3d_lines')
_ensure(Question, {'question_id': '2025Paper2Q1'}, marks=2, question_id='2025Paper2Q1', question_number='1', video='', paper='2025 Paper 2', topics='differentiation', subtopics='new_functions,chain_rule')
_ensure(Question, {'question_id': '2025Paper2Q2'}, marks=3, question_id='2025Paper2Q2', question_number='2', video='', paper='2025 Paper 2', topics='differentiation', subtopics='implicit,product_rule,chain_rule')
_ensure(Question, {'question_id': '2025Paper2Q3'}, marks=3, question_id='2025Paper2Q3', question_number='3', video='', paper='2025 Paper 2', topics='partial_fractions', subtopics='distinct_linear_factors')
_ensure(Question, {'question_id': '2025Paper2Q4'}, marks=3, question_id='2025Paper2Q4', question_number='4', video='', paper='2025 Paper 2', topics='number_theory', subtopics='euclidean_algorithm')
_ensure(Question, {'question_id': '2025Paper2Q5'}, marks=5, question_id='2025Paper2Q5', question_number='5', video='', paper='2025 Paper 2', topics='differentiation', subtopics='logarithmic,product_rule')
_ensure(Question, {'question_id': '2025Paper2Q6a'}, marks=2, question_id='2025Paper2Q6a', question_number='6a', video='', paper='2025 Paper 2', topics='maclaurin_series', subtopics='simple_functions')
_ensure(Question, {'question_id': '2025Paper2Q6b'}, marks=2, question_id='2025Paper2Q6b', question_number='6b', video='', paper='2025 Paper 2', topics='maclaurin_series', subtopics='combining_expansions')
_ensure(Question, {'question_id': '2025Paper2Q7'}, marks=5, question_id='2025Paper2Q7', question_number='7', video='', paper='2025 Paper 2', topics='differentiation', subtopics='parametric,second_derivative,quotient_rule')
_ensure(Question, {'question_id': '2025Paper2Q8'}, marks=4, question_id='2025Paper2Q8', question_number='8', video='', paper='2025 Paper 2', topics='matrices', subtopics='matrix_algebra_identities,inverse_matrices')
_ensure(Question, {'question_id': '2025Paper2Q9'}, marks=4, question_id='2025Paper2Q9', question_number='9', video='', paper='2025 Paper 2', topics='differentiation,integration', subtopics='speed_acceleration,standard_integrals')
_ensure(Question, {'question_id': '2025Paper2Q10'}, marks=2, question_id='2025Paper2Q10', question_number='10', video='', paper='2025 Paper 2', topics='sequences_series', subtopics='summation_formulae')
_ensure(Question, {'question_id': '2025Paper2Q11'}, marks=5, question_id='2025Paper2Q11', question_number='11', video='', paper='2025 Paper 2', topics='integration', subtopics='substitution,volumes_of_revolution')
_ensure(Question, {'question_id': '2025Paper2Q12'}, marks=9, question_id='2025Paper2Q12', question_number='12', video='', paper='2025 Paper 2', topics='differential_equations', subtopics='second_order_non_homogeneous')
_ensure(Question, {'question_id': '2025Paper2Q13'}, marks=7, question_id='2025Paper2Q13', question_number='13', video='', paper='2025 Paper 2', topics='sequences_series', subtopics='geometric_progressions')
_ensure(Question, {'question_id': '2025Paper2Q14'}, marks=5, question_id='2025Paper2Q14', question_number='14', video='', paper='2025 Paper 2', topics='differential_equations', subtopics='first_order_integrating_factor')
_ensure(Question, {'question_id': '2025Paper2Q15'}, marks=5, question_id='2025Paper2Q15', question_number='15', video='', paper='2025 Paper 2', topics='methods_of_proof', subtopics='induction')
_ensure(Question, {'question_id': '2025Paper2Q16'}, marks=5, question_id='2025Paper2Q16', question_number='16', video='', paper='2025 Paper 2', topics='integration', subtopics='parts')
_ensure(Question, {'question_id': '2025Paper2Q17'}, marks=4, question_id='2025Paper2Q17', question_number='17', video='', paper='2025 Paper 2', topics='differentiation', subtopics='related_rates')
_ensure(Question, {'question_id': '2025Paper2Q18'}, marks=5, question_id='2025Paper2Q18', question_number='18', video='', paper='2025 Paper 2', topics='complex_numbers', subtopics='basic_operations,argand_diagrams_polar_form,de_moivres_theorem')
"""
